# Generated by Django 3.0 on 2020-01-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timevalue',
            options={'verbose_name': 'Данные клиента', 'verbose_name_plural': 'Данные клиента'},
        ),
    ]
