# Generated by Django 3.0 on 2020-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCount',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
            },
        ),
    ]
